- name: show version and other user level commands
  hosts: all

  tasks:
    - name: run multiple commands on remote nodes
      ios_command:
        commands:
          - show version
          - show ip int brief
          - show ip interface brief | exclude down


      register: print_output

    -  debug: var=print_output.stdout_lines


